export const types = {
  GET_RESTAURANT_LIST: "GET_RESTAURANT_LIST",
  GET_RESTAURANT_LIST_SUCCESS: "GET_RESTAURANT_LIST_SUCCESS",
  GET_RESTAURANT_LIST_FAILURE: "GET_RESTAURANT_LIST_FAILURE",
  SAVE_CURRENT_POSITION: "SAVE_CURRENT_POSITION",
  SEARCH_BY_NAME: "SEARCH_BY_NAME"
};
